### ISSUE TITLE
Error with piplaystate.py in normal mode

### ISSUE THREAD

**Issue by MoeFwacky** [amazingr4b/TBN-Plex#21]
When running in normal mode, it kicks this error. Block mode seems to work fine

Trying to start:

Traceback (most recent call last):
  File "/home/pi/hasystem//system.py", line 7245, in <module>
    startnextprogram()
  File "/home/pi/hasystem//system.py", line 6527, in startnextprogram
    say = playshow(show)
  File "/home/pi/hasystem//system.py", line 3104, in playshow
    for video in plex.search(cshow):
  File "/usr/local/lib/python2.7/dist-packages/plexapi/server.py", line 116, in search
    items = utils.listItems(self, '/search?query=%s' % quote(query))
  File "/usr/local/lib/python2.7/dist-packages/plexapi/utils.py", line 232, in listItems
    for elem in server.query(path):
  File "/usr/local/lib/python2.7/dist-packages/plexapi/server.py", line 110, in query
    raise BadRequest('(%s) %s' % (response.status_code, codename))
plexapi.exceptions.BadRequest: (404) not_found

**Comment by amazingr4b** [comment]
While having the output is nice, the output alone doesn't provide enough information to try and help with issues like this. What version of the system script are you running(versioncheck)? When you do a whatupnext what does it say it was trying to play? Did you confirm that item exists in your library? Is the file duplicated in the library or another library? Try the queuefix command? Knowing that kind of stuff would help.

**Comment by MoeFwacky** [comment]
Running version 3.01e

Looks like queuefix did the job. Not a problem anymore.
