### ISSUE TITLE
Issue with install?

### ISSUE THREAD

**Issue by erikmellum** [amazingr4b/TBN-Plex#25]
I get the following error when running `system.py`
```
Would you like to update your system database now to add the available shows and movies in your library?
Yes or No? Yes
python: can't open file '.hasystemupddatedb_pi.py': [Errno 2] No such file or directory
If you needed that entry for cron it was: @reboot python /home/pi/hasystem/piplaystate.py &
```

Do you know why that is missing?

**Comment by MoeFwacky** [comment]
Did you run the system_setup.py file from your /home/pi directory first?

**Comment by erikmellum** [comment]
I'm running on a mac not on a raspberry pi server so I don't have that directory. Unclear if I should run it from that directory despite this?

**Comment by erikmellum** [comment]
I actually can't even place any files in my /home directory.

**Comment by MoeFwacky** [comment]
Hmm, not sure about installation on a non-linux device, but run the setup from a folder you can place it in. It should create a subfolder called hasystem and download the rest of the necessary script files into it. Those files should have the right file pathing automatically inserted by the setup.

**Comment by amazingr4b** [comment]
Whelp. The current setup script looks at your os type and only supports linux and windows. I don't currently have any IOS devices to test with to find how the folders and paths need to be setup. I suppose you could do a manual install by placing all the files in a directory, adding "homedir = "pathtothatdir"" to the top of the .py files, and then creating the couple text files it uses. I'll see if I can find some time later this week to write up a better step by step from installing without using the setup script.

**Comment by erikmellum** [comment]
I customized the homedir in a few scripts and got up to this poin:

96.8%Traceback (most recent call last):
  File "./hasystem/upddatedb_pi.py", line 665, in <module>
    getmovies()
  File "./hasystem/upddatedb_pi.py", line 203, in getmovies
    cur.execute('INSERT INTO Movies VALUES(?, ?, ?, ?, ?, ?, ?)', (name, summary, rating, tagline, bgenre, directors, bactors))
sqlite3.ProgrammingError: You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings.
If you needed that entry for cron it was: @reboot python /home/pi/hasystem/piplaystate.py &

**Comment by erikmellum** [comment]
I'll see if I can get it up and running on mac. Branch is located (here:)[https://github.com/erikmellum/TBN-Plex/tree/mac-compatibility]

**Comment by erikmellum** [comment]
Worked through the previous issue by switching: 
```python
cur.execute('INSERT INTO Movies VALUES(?, ?, ?, ?, ?, ?, ?)', name, summary, rating, tagline, bgenre, directors, bactors))
```
to
```python
cur.execute('INSERT INTO Movies VALUES(?, ?, ?, ?, ?, ?, ?)', (sqlite3.Binary(name), summary, rating, tagline, bgenre, directors, bactors))
```

I got this output for every movie (may be normal... not sure):
```bash
Problems getting episode count for: A Walk to Remember. Check this item in your plex db. Setting to 1 for now and moving on.
```
That went on for a while before I received this error: 
```
96.6%Traceback (most recent call last):
  File "./hasystem/upddatedb_pi.py", line 667, in <module>
    getshows()
  File "./hasystem/upddatedb_pi.py", line 335, in getshows
    name = str(show.title)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb7' in position 4: ordinal not in range(128)
If you needed that entry for cron it was: @reboot python /home/pi/hasystem/piplaystate.py &
```

I'll see what I can do to get around this one. I've never written python before so this will be interesting lol.

**Comment by amazingr4b** [comment]
Getting "Problems getting episode count for..." for a movie item is not normal. You'd normally only get that if there was a problem getting the number of episodes for a given show... Judging by the line, I'm guessing you specified your movies library where it was looking for the TV Shows. 

If you go to the end of your library, what is the title for the item that would represent the 96.6%? The update I just posted should theoretically eliminate that errror, but it would be nice to know what title was causing it.

**Comment by erikmellum** [comment]
I was able to get past all of those errors. Now I'm hitting this:

```
Eriks-MBP-2:TBN-Plex emellum$ whatupnext
First run situation detected. Taking approprate action.

Traceback (most recent call last):
  File "/Users/emellum/Desktop/projects/TBN-Plex/hasystem/system.py", line 7483, in <module>
    say = whatupnext()
  File "/Users/emellum/Desktop/projects/TBN-Plex/hasystem/system.py", line 5440, in whatupnext
    the_show = shows.get(playme).episodes()
  File "/Library/Python/2.7/site-packages/plexapi/library.py", line 129, in get
    return utils.findItem(self.server, path, title)
  File "/Library/Python/2.7/site-packages/plexapi/utils.py", line 162, in findItem
    raise NotFound('Unable to find item: %s' % title)
plexapi.exceptions.NotFound: Unable to find item: *
```

Can you explain the Wildcard TV Show a little bit to me? I've tried:
* The Office
* A Walk to Remember
* *

As Wildcard TV Shows and I get the error above for each.

**Comment by erikmellum** [comment]
Separately in regards to some of your previous comments:

1. Yes I did accidentally specify my "Movies" library for TV Shows. I didn't read the output carefully enough. That one is resolved now.
2. I'm not sure what title was causing that encode error. It didn't output the name of the movie before the crash. I think I can drop the fix into the Exception handler and output the filename. So give me a second and I'll see if I can grab that...

**Comment by amazingr4b** [comment]
I think of the "wild card show" as the TV show I'm currently working on getting through. The play checking mechanism will automatically pick content from your movies and tv shows, and when you have created blocks or added custom libraries it includes those as well in the pool of available options it picks from. The wild card show is setup as a item in that pool independent of the tv shows/other show libraries available. This causes it to be picked more often than other shows. 

do a "listwildcard" and make sure the option you selected on setup was actually saved.

**Comment by erikmellum** [comment]
I think I needed to wrap quotes around "The Office". I used Seinfeld and it seems to work. It looks like the initial install is done now. I put in a pull request that updates the README.md to a little bit more digestible format. Please take a look at that and let me know if you have any suggestions. If not maybe you could merge it in? I'm thinking about building a UI around this but I want to get a handle on how I would use it myself before I dive down that rabbit hole.

**Comment by amazingr4b** [comment]
The quotes thing usually depends on where you are entering it. Command line you'll need to "" around anything with spaces in it. Usually where it promps you, like in the setup script, you don't need them. Some commands, like changewildcard and addblock, support both command line and prompt entry modes, ie:
changewildcard
 with no arguments will then prompt you for the wild card. 

you can also use it like:
changewildcard "show name goes here"

it will use the argument to set the show and skip the prompt. 

The body of my readme needs to be updated. It is quite outdated at this point. For example, it does not mention the gethelp function. You can do "python system.py updatehelp" to get the most recent help entries and add them to the database. Once you've done that you can add the "-h" flag to the vast majority of the commands to get some help info. I don't think it mentions "-l" either. I need to update stuff like that. For the most part the commands are good, though safe to say a fair amount of new ones are missing.

**Comment by amazingr4b** [comment]
I'm curious, when you first ran the system_setup.py script, did it ask you where you wanted to put your home directory? If it did, what did you enter?

**Comment by erikmellum** [comment]
Yes it asked. I was using `./` as my directory.

**Comment by amazingr4b** [comment]
Try it with your full path to your disired directory there instead of the ./.

**Comment by erikmellum** [comment]
I also tried with the full path and it didn't act any differently than using ./

**Comment by amazingr4b** [comment]
What is the path you tried?

**Comment by erikmellum** [comment]
`/Users/emellum/Desktop/projects/TBN-Plex/`

**Comment by amazingr4b** [comment]
The system_setup.py file I just added might now work for you. I don't currently have a way to test the macos part, unfortunately.

**Comment by erikmellum** [comment]
I did get a chance to try last night but there are some additional changes that need to be made. I'll submit those changes in a pull request. I'd appreciate it if you could merge them in if you think they are good. I was bummed out that you didn't merge my updates to the readme.md. It looks like you used some of them in your own commit :/. I was hoping to contribute a couple commits where I could!

I'll finish that work in a few days. I'll be away for Thanksgiving and the IP addresses retrieved for a given plex server are for use on a local network. That unfortunately will prevent me from testing while I'm away from home.

Also as an observation I noticed that my plex server was ignoring all traffic after a few failed executions of system_setup.py. (The homedir still needs a little bit more love to fully get through `upddate_db.py`). I'm not sure if you have seen that before, but it seemed to start allowing traffic again after waiting for some duration of time (probably about 10 - 15 minutes). 

Lastly I think I might make some additional changes to start encrypting and salting passwords stored in the DB. Updates on that to come.

**Comment by amazingr4b** [comment]
Had I not rewrote the entire readme I would have just merged it. 

I've not tried a using a remote server, though I see what you mean about the local address. I'll add some actions to manually set that. From what I recall multiple ips are listed, and the setup script grabs the first ip, which tends to be the local one even if you are not local to the server. Not sure how well things will work with the non-local stuff, but its worth a shot.  

That doesn't seem like typical behavior, and is not a problem i've heard of/experienced. I cant comment on what your firewall or other security programs might be doing.   

If someone has their plex server setup to allow access from the controller without authorization then the password is not needed. Given that that is the preferred method of using this script, I've been thinking of completely removing the stored password all together. I figure on the rare occasion it is needed the user can be prompted to enter it. If I don't take that route I'm going to figure something out so the password is stored better. I'm not a fan of how that is currently done myself.
